packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@expo/cli@57.0.6"
  - "@expo/config@57.0.3"
  - "@types/node@26.1.1"
  - expo-modules-core@57.0.3
  - expo-modules-jsi@57.0.1
  - expo@57.0.4
